networks:
  ethplayground:
    name: ethplayground
services:
  beacon:
    command:
    - bn
    - --datadir
    - /data_beacon
    - --testnet-dir
    - /data/testnet-dir
    - --enable-private-discovery
    - --disable-peer-scoring
    - --staking
    - --enr-address
    - 127.0.0.1
    - --enr-udp-port
    - "9000"
    - --enr-tcp-port
    - "9000"
    - --enr-quic-port
    - "9100"
    - --port
    - "9000"
    - --quic-port
    - "9100"
    - --http
    - --http-port
    - "3500"
    - --http-address
    - 0.0.0.0
    - --http-allow-origin
    - '*'
    - --disable-packet-filter
    - --target-peers
    - "0"
    - --execution-endpoint
    - http://el:8551
    - --execution-jwt
    - /data/jwtsecret
    - --always-prepare-payload
    - --prepare-payload-lookahead
    - "8000"
    - --suggested-fee-recipient
    - 0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990
    entrypoint: lighthouse
    extra_hosts:
      host.docker.internal: 172.17.0.1
    healthcheck:
      interval: 1s
      retries: 3
      start_period: 1s
      test:
      - CMD-SHELL
      - chmod +x /artifacts/scripts/query.sh && /artifacts/scripts/query.sh http://localhost:3500/eth/v1/node/syncing
      timeout: 30s
    image: sigp/lighthouse:v7.0.0-beta.0
    labels:
      playground: "true"
      playground.session: f643c827-7708-4ab9-9805-3610153696ef
      port.http: "3500"
      port.p2p: "9000"
      port.quic-p2p: "9100"
      service: beacon
    networks:
    - ethplayground
    ports:
    - 127.0.0.1:9000:9000/udp
    - 127.0.0.1:9001:9000
    - 127.0.0.1:9101:9100
    - 127.0.0.1:3500:3500
    volumes:
    - /home/pyuhala/.playground/devnet:/artifacts
    - /home/pyuhala/.playground/devnet/testnet:/data/testnet-dir
    - /home/pyuhala/.playground/devnet/jwtsecret:/data/jwtsecret
    - /home/pyuhala/.playground/devnet/volume-beacon-data:/data_beacon
  el:
    command:
    - node
    - --chain
    - /data/genesis.json
    - --datadir
    - /data_reth
    - --color
    - never
    - --ipcpath
    - /data_reth/reth.ipc
    - --addr
    - 127.0.0.1
    - --port
    - "30303"
    - --http
    - --http.addr
    - 0.0.0.0
    - --http.api
    - admin,eth,web3,net,rpc,mev,flashbots
    - --http.port
    - "8545"
    - --ws
    - --ws.addr
    - 0.0.0.0
    - --ws.port
    - "8546"
    - --ws.api
    - eth,web3,net,txpool,debug,trace
    - --ws.origins
    - '*'
    - --authrpc.port
    - "8551"
    - --authrpc.addr
    - 0.0.0.0
    - --authrpc.jwtsecret
    - /data/jwtsecret
    - --metrics
    - 0.0.0.0:9090
    - --engine.persistence-threshold
    - "0"
    - --engine.memory-block-buffer-target
    - "0"
    - -vvv
    entrypoint: /usr/local/bin/reth
    extra_hosts:
      host.docker.internal: 172.17.0.1
    image: ghcr.io/paradigmxyz/reth:v1.4.8
    labels:
      playground: "true"
      playground.session: f643c827-7708-4ab9-9805-3610153696ef
      port.authrpc: "8551"
      port.http: "8545"
      port.metrics: "9090"
      port.rpc: "30303"
      port.ws: "8546"
      service: el
    networks:
    - ethplayground
    ports:
    - 127.0.0.1:30303:30303
    - 127.0.0.1:8545:8545
    - 127.0.0.1:8546:8546
    - 127.0.0.1:8551:8551
    - 127.0.0.1:9091:9090
    volumes:
    - /home/pyuhala/.playground/devnet/genesis.json:/data/genesis.json
    - /home/pyuhala/.playground/devnet/jwtsecret:/data/jwtsecret
    - /home/pyuhala/.playground/devnet/volume-el-data:/data_reth
    - /home/pyuhala/.playground/devnet:/artifacts
  op-batcher:
    command:
    - --l1-eth-rpc
    - http://el:8545
    - --l2-eth-rpc
    - http://op-geth:8545
    - --rollup-rpc
    - http://op-node:8549
    - --max-channel-duration=2
    - --sub-safety-margin=4
    - --poll-interval=1s
    - --num-confirmations=1
    - --private-key=0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6
    entrypoint: op-batcher
    extra_hosts:
      host.docker.internal: 172.17.0.1
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-batcher:v1.12.0-rc.1
    labels:
      playground: "true"
      playground.session: f643c827-7708-4ab9-9805-3610153696ef
      service: op-batcher
    networks:
    - ethplayground
    volumes:
    - /home/pyuhala/.playground/devnet:/artifacts
  op-geth:
    command:
    - -c
    - geth init --datadir /data_opgeth --state.scheme hash /data/l2-genesis.json &&
      exec geth --datadir /data_opgeth --verbosity 3 --http --http.corsdomain "*"
      --http.vhosts "*" --http.addr 0.0.0.0 --http.port 8545 --http.api web3,debug,eth,txpool,net,engine,miner
      --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins "*" --ws.api debug,eth,txpool,net,engine,miner
      --syncmode full --nodiscover --maxpeers 5 --rpc.allow-unprotected-txs --authrpc.addr
      0.0.0.0 --authrpc.port 8551 --authrpc.vhosts "*" --authrpc.jwtsecret /data/jwtsecret
      --gcmode archive --state.scheme hash --port 30303 --nodekey /data/p2p_key.txt
      --metrics --metrics.addr 0.0.0.0 --metrics.port 6061
    entrypoint: /bin/sh
    extra_hosts:
      host.docker.internal: 172.17.0.1
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101503.2-rc.5
    labels:
      playground: "true"
      playground.session: f643c827-7708-4ab9-9805-3610153696ef
      port.authrpc: "8551"
      port.http: "8545"
      port.metrics: "6061"
      port.rpc: "30303"
      port.ws: "8546"
      service: op-geth
    networks:
    - ethplayground
    ports:
    - 127.0.0.1:8547:8545
    - 127.0.0.1:8548:8546
    - 127.0.0.1:8552:8551
    - 127.0.0.1:30304:30303
    - 127.0.0.1:6061:6061
    volumes:
    - /home/pyuhala/.playground/devnet:/artifacts
    - /home/pyuhala/.playground/devnet/l2-genesis.json:/data/l2-genesis.json
    - /home/pyuhala/.playground/devnet/jwtsecret:/data/jwtsecret
    - /home/pyuhala/.playground/devnet/enode-key-1.txt:/data/p2p_key.txt
    - /home/pyuhala/.playground/devnet/volume-op-geth-data:/data_opgeth
  op-node:
    command:
    - --l1
    - http://el:8545
    - --l1.beacon
    - http://beacon:3500
    - --l1.epoch-poll-interval
    - 12s
    - --l1.http-poll-interval
    - 6s
    - --l2
    - http://rollup-boost:8551
    - --l2.jwt-secret
    - /data/jwtsecret
    - --sequencer.enabled
    - --sequencer.l1-confs
    - "0"
    - --verifier.l1-confs
    - "0"
    - --p2p.sequencer.key
    - 8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba
    - --rollup.config
    - /data/rollup.json
    - --rpc.addr
    - 0.0.0.0
    - --rpc.port
    - "8549"
    - --p2p.listen.ip
    - 0.0.0.0
    - --p2p.listen.tcp
    - "9003"
    - --p2p.listen.udp
    - "9003"
    - --p2p.scoring.peers
    - light
    - --p2p.ban.peers
    - "true"
    - --metrics.enabled
    - --metrics.addr
    - 0.0.0.0
    - --metrics.port
    - "7300"
    - --pprof.enabled
    - --rpc.enable-admin
    - --safedb.path
    - /data_db
    entrypoint: op-node
    environment:
      A: B
    extra_hosts:
      host.docker.internal: 172.17.0.1
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node:v1.13.0-rc.1
    labels:
      playground: "true"
      playground.session: f643c827-7708-4ab9-9805-3610153696ef
      port.http: "8549"
      port.metrics: "7300"
      port.p2p: "9003"
      service: op-node
    networks:
    - ethplayground
    ports:
    - 127.0.0.1:8549:8549
    - 127.0.0.1:9003:9003
    - 127.0.0.1:9004:9003/udp
    - 127.0.0.1:7300:7300
    volumes:
    - /home/pyuhala/.playground/devnet:/artifacts
    - /home/pyuhala/.playground/devnet/jwtsecret:/data/jwtsecret
    - /home/pyuhala/.playground/devnet/rollup.json:/data/rollup.json
    - /home/pyuhala/.playground/devnet/volume-op-node-data:/data_db
  rollup-boost:
    command:
    - --rpc-host
    - 0.0.0.0
    - --rpc-port
    - "8551"
    - --l2-jwt-path
    - /data/jwtsecret
    - --l2-url
    - http://op-geth:8551
    - --builder-jwt-path
    - /data/jwtsecret
    - --builder-url
    - http://host:8555
    extra_hosts:
      host.docker.internal: 172.17.0.1
    image: docker.io/flashbots/rollup-boost:0.7.0
    labels:
      playground: "true"
      playground.session: f643c827-7708-4ab9-9805-3610153696ef
      port.authrpc: "8551"
      service: rollup-boost
    networks:
    - ethplayground
    ports:
    - 127.0.0.1:8553:8551
    volumes:
    - /home/pyuhala/.playground/devnet:/artifacts
    - /home/pyuhala/.playground/devnet/jwtsecret:/data/jwtsecret
  validator:
    command:
    - vc
    - --datadir
    - /data/validator
    - --testnet-dir
    - /data/testnet-dir
    - --init-slashing-protection
    - --beacon-nodes
    - http://beacon:3500
    - --suggested-fee-recipient
    - 0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990
    - --builder-proposals
    - --prefer-builder-proposals
    entrypoint: lighthouse
    extra_hosts:
      host.docker.internal: 172.17.0.1
    image: sigp/lighthouse:v7.0.0-beta.0
    labels:
      playground: "true"
      playground.session: f643c827-7708-4ab9-9805-3610153696ef
      service: validator
    networks:
    - ethplayground
    volumes:
    - /home/pyuhala/.playground/devnet:/artifacts
    - /home/pyuhala/.playground/devnet/data_validator:/data/validator
    - /home/pyuhala/.playground/devnet/testnet:/data/testnet-dir
