apiVersion: v1
kind: Pod
metadata:
  name: nginx-kata
  labels:
    run: nginx-kata
spec:
  runtimeClassName: kata-qemu-tdx
  containers:
    - name: nginx
      image: ubuntu:24.04
      imagePullPolicy: Always
      command: ["/bin/bash", "-c", "--"]
      args: ["apt update && apt install -y nginx && nginx -g 'daemon off;'"]
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    run: nginx-kata
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
