apiVersion: v1
kind: Pod
metadata:
  name: hello-kata-pod
  labels:
    app: hello
spec:
  runtimeClassName: kata-qemu-tdx  
  containers:
    - name: hello
      image: busybox
      command: ['sh', '-c']
      args:
        - while true; do
            echo "Hello from container 1!";
            sleep 5;
          done

    - name: world
      image: busybox
      command: ['sh', '-c']
      args:
        - while true; do
            echo "Logging from sidecar... 2";
            sleep 10;
          done

  restartPolicy: Always